-- Create a database Schema
DROP DATABASE IF EXISTS ETL_PROJECT;
CREATE DATABASE ETL_PROJECT;

USE ETL_PROJECT;
-- Create a table to store airlines data
DROP TABLE IF EXISTS US_AIRLINES_STATS;
CREATE TABLE US_AIRLINES_STATS (
	`IATA_CODE` VARCHAR(2) CHARACTER SET utf8,
    `AIRLINE` VARCHAR(50) CHARACTER SET utf8,
	`DEPARTURE_DELAYS` INT,
	`ARRIVAL_DELAYS` INT,
	`TOTAL_INCIDENTS` INT,
	`PASSENGERS_TRAVELLED` INT
);

select * from US_AIRLINES_STATS;